export enum ENDPOINT_PATH {
	GET_AGENDA = '/agenda',
	GET_AGENDA_BY_ID = '/agenda/:id',
	GET_NEWS = '/news',
	GET_NEWS_BY_SLUG = '/news/:slug',
	GET_CITY_INDEX = '/index',
	GET_SERVICE = '/app',
	GET_SERVICE_CLUSTER = '/cluster',
	GET_SERVICE_ORG = '/dinas',
	GET_ORG_DETAILS = '/service-org',
	GET_SEARCH = '/search',
	GET_SERVICE_SEARCH = '/app/search',
	GET_SERVICE_SEARCH_HIGHLIGHT = '/app/searchHighlight',
	GET_NEWS_SEARCH = '/news/search',
	GET_NEWS_SEARCH_HIGHLIGHT = '/news/searchHighlight',
	GET_AGENDA_SEARCH = '/agenda/search',
	GET_AGENDA_SEARCH_HIGHLIGHT = '/agenda/searchHighlight',
	GET_CITY_INDEX_SEARCH = '/index/search',
	GET_CITY_INDEX_SEARCH_HIGHLIGHT = '/index/searchHighlight',
}
